### ISSUE TITLE
install: missing blinker depencency

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-base#55]
Scenario:
```shell
$ pip install invenio-base
$ inveniomanage instance create myapp
```
Result:
```
Traceback (most recent call last):
  File "/Users/nharraud/.virtualenvs/b2share-scratch/bin/inveniomanage", line 7, in <module>
    from invenio_base.manage import main
  File "/Users/nharraud/.virtualenvs/b2share-scratch/lib/python2.7/site-packages/invenio_base/manage.py", line 25, in <module>
    from .factory import create_app
  File "/Users/nharraud/.virtualenvs/b2share-scratch/lib/python2.7/site-packages/invenio_base/factory.py", line 47, in <module>
    from .wrappers import Flask
  File "/Users/nharraud/.virtualenvs/b2share-scratch/lib/python2.7/site-packages/invenio_base/wrappers.py", line 75, in <module>
    from .signals import before_handle_user_exception
  File "/Users/nharraud/.virtualenvs/b2share-scratch/lib/python2.7/site-packages/invenio_base/signals.py", line 26, in <module>
    from blinker import Namespace
ImportError: No module named blinker
```

**Comment by nharraud** [comment]
My bad, forgot to use `--pre` in `pip install`.
I saw at the same time that the alpha releases' documentation pages are not including the `--pre` either in the installation steps.
